packages:
  - apps/*
  - packages/*

catalog:
  '@aws-sdk/client-dynamodb': 3.907.0
  '@aws-sdk/client-s3': 3.907.0
  '@aws-sdk/lib-dynamodb': 3.907.0
  '@aws-sdk/s3-request-presigner': 3.907.0
  '@eslint/js': 9.37.0
  '@types/aws-lambda': ^8.10.0
  '@types/node': 24.7.1
  '@types/react': 19.2.2
  '@types/react-dom': 19.2.2
  '@typescript-eslint/eslint-plugin': 8.46.0
  '@typescript-eslint/parser': 8.46.0
  '@vitejs/plugin-react': 5.1.0
  autoprefixer: 10.4.22
  class-variance-authority: 0.7.1
  clsx: 2.1.1
  eslint: 9.37.0
  eslint-plugin-react-hooks: 7.0.1
  eslint-plugin-react-refresh: 0.4.24
  framer-motion: 12.23.24
  globals: 16.5.0
  hono: 4.6.11
  lucide-react: 0.554.0
  postcss: 8.5.6
  prettier: 3.6.2
  react: 19.2.0
  react-dom: 19.2.0
  tailwind-merge: 3.4.0
  tailwindcss: 4.1.17
  tsup: 8.5.0
  turbo: 2.6.1
  tw-animate-css: 1.4.0
  typescript: 5.9.3
  typescript-eslint: 8.46.0
  vite: 7.2.2
  vitest: 2.1.8
  sst: 3.17.23
  '@radix-ui/react-dialog': 1.1.15
  '@radix-ui/react-dropdown-menu': 2.1.16
  '@radix-ui/react-progress': 1.1.8
  '@radix-ui/react-select': 2.2.6
  '@radix-ui/react-slot': 1.2.4
  '@tailwindcss/postcss': 4.1.17
  sonner: 2.0.7
