packages:
  - apps/*
  - packages/*

catalog:
  '@aws-sdk/client-s3': 3.907.0
  '@aws-sdk/s3-request-presigner': 3.907.0
  '@eslint/js': 9.37.0
  '@types/aws-lambda': ^8.10.0
  '@types/node': 24.7.1
  '@typescript-eslint/eslint-plugin': 8.46.0
  '@typescript-eslint/parser': 8.46.0
  eslint: 9.37.0
  hono: 4.6.11
  prettier: 3.6.2
  tsup: 8.5.0
  turbo: 2.6.0
  typescript: 5.9.3
  typescript-eslint: 8.46.0
  vitest: 2.1.8
